/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToysIndexRouteImport } from './routes/toys/index'
import { Route as ChildrenIndexRouteImport } from './routes/children/index'
import { Route as ToysNewRouteImport } from './routes/toys/new'
import { Route as ChildrenNewRouteImport } from './routes/children/new'
import { Route as ToysIdIndexRouteImport } from './routes/toys/$id/index'
import { Route as ChildrenIdIndexRouteImport } from './routes/children/$id/index'
import { Route as ToysIdEditRouteImport } from './routes/toys/$id/edit'
import { Route as ChildrenIdEditRouteImport } from './routes/children/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToysIndexRoute = ToysIndexRouteImport.update({
  id: '/toys/',
  path: '/toys/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenIndexRoute = ChildrenIndexRouteImport.update({
  id: '/children/',
  path: '/children/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToysNewRoute = ToysNewRouteImport.update({
  id: '/toys/new',
  path: '/toys/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenNewRoute = ChildrenNewRouteImport.update({
  id: '/children/new',
  path: '/children/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ToysIdIndexRoute = ToysIdIndexRouteImport.update({
  id: '/toys/$id/',
  path: '/toys/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenIdIndexRoute = ChildrenIdIndexRouteImport.update({
  id: '/children/$id/',
  path: '/children/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToysIdEditRoute = ToysIdEditRouteImport.update({
  id: '/toys/$id/edit',
  path: '/toys/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenIdEditRoute = ChildrenIdEditRouteImport.update({
  id: '/children/$id/edit',
  path: '/children/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/children/new': typeof ChildrenNewRoute
  '/toys/new': typeof ToysNewRoute
  '/children': typeof ChildrenIndexRoute
  '/toys': typeof ToysIndexRoute
  '/children/$id/edit': typeof ChildrenIdEditRoute
  '/toys/$id/edit': typeof ToysIdEditRoute
  '/children/$id': typeof ChildrenIdIndexRoute
  '/toys/$id': typeof ToysIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/children/new': typeof ChildrenNewRoute
  '/toys/new': typeof ToysNewRoute
  '/children': typeof ChildrenIndexRoute
  '/toys': typeof ToysIndexRoute
  '/children/$id/edit': typeof ChildrenIdEditRoute
  '/toys/$id/edit': typeof ToysIdEditRoute
  '/children/$id': typeof ChildrenIdIndexRoute
  '/toys/$id': typeof ToysIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/children/new': typeof ChildrenNewRoute
  '/toys/new': typeof ToysNewRoute
  '/children/': typeof ChildrenIndexRoute
  '/toys/': typeof ToysIndexRoute
  '/children/$id/edit': typeof ChildrenIdEditRoute
  '/toys/$id/edit': typeof ToysIdEditRoute
  '/children/$id/': typeof ChildrenIdIndexRoute
  '/toys/$id/': typeof ToysIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/children/new'
    | '/toys/new'
    | '/children'
    | '/toys'
    | '/children/$id/edit'
    | '/toys/$id/edit'
    | '/children/$id'
    | '/toys/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/children/new'
    | '/toys/new'
    | '/children'
    | '/toys'
    | '/children/$id/edit'
    | '/toys/$id/edit'
    | '/children/$id'
    | '/toys/$id'
  id:
    | '__root__'
    | '/'
    | '/children/new'
    | '/toys/new'
    | '/children/'
    | '/toys/'
    | '/children/$id/edit'
    | '/toys/$id/edit'
    | '/children/$id/'
    | '/toys/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChildrenNewRoute: typeof ChildrenNewRoute
  ToysNewRoute: typeof ToysNewRoute
  ChildrenIndexRoute: typeof ChildrenIndexRoute
  ToysIndexRoute: typeof ToysIndexRoute
  ChildrenIdEditRoute: typeof ChildrenIdEditRoute
  ToysIdEditRoute: typeof ToysIdEditRoute
  ChildrenIdIndexRoute: typeof ChildrenIdIndexRoute
  ToysIdIndexRoute: typeof ToysIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toys/': {
      id: '/toys/'
      path: '/toys'
      fullPath: '/toys'
      preLoaderRoute: typeof ToysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/': {
      id: '/children/'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof ChildrenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toys/new': {
      id: '/toys/new'
      path: '/toys/new'
      fullPath: '/toys/new'
      preLoaderRoute: typeof ToysNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/new': {
      id: '/children/new'
      path: '/children/new'
      fullPath: '/children/new'
      preLoaderRoute: typeof ChildrenNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toys/$id/': {
      id: '/toys/$id/'
      path: '/toys/$id'
      fullPath: '/toys/$id'
      preLoaderRoute: typeof ToysIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/$id/': {
      id: '/children/$id/'
      path: '/children/$id'
      fullPath: '/children/$id'
      preLoaderRoute: typeof ChildrenIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toys/$id/edit': {
      id: '/toys/$id/edit'
      path: '/toys/$id/edit'
      fullPath: '/toys/$id/edit'
      preLoaderRoute: typeof ToysIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/$id/edit': {
      id: '/children/$id/edit'
      path: '/children/$id/edit'
      fullPath: '/children/$id/edit'
      preLoaderRoute: typeof ChildrenIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChildrenNewRoute: ChildrenNewRoute,
  ToysNewRoute: ToysNewRoute,
  ChildrenIndexRoute: ChildrenIndexRoute,
  ToysIndexRoute: ToysIndexRoute,
  ChildrenIdEditRoute: ChildrenIdEditRoute,
  ToysIdEditRoute: ToysIdEditRoute,
  ChildrenIdIndexRoute: ChildrenIdIndexRoute,
  ToysIdIndexRoute: ToysIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
